# Generated by Django 4.2.13 on 2026-05-23 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='rider',
            field=models.OneToOneField(limit_choices_to={'role': 'RIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderlocationhistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_locations', to='orders.order'),
        ),
        migrations.AddField(
            model_name='riderlocationhistory',
            name='rider',
            field=models.ForeignKey(limit_choices_to={'role': 'RIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='riderlocationhistory',
            index=models.Index(fields=['rider', 'recorded_at'], name='rider_locat_rider_i_e99099_idx'),
        ),
        migrations.AddIndex(
            model_name='riderlocationhistory',
            index=models.Index(fields=['order'], name='rider_locat_order_i_16816b_idx'),
        ),
    ]
